### ISSUE TITLE
License of the project

### ISSUE THREAD

**Issue by bbinet** [Dherse/ugent-templates#1]
Thank you for sharing this great typst template!

I would like to use it in my small 3-people company (after doing some minor colors updates).
What it the license of the project and is it allowed to use in a company?

**Comment by Dherse** [comment]
Hey, as far as I'm concerned, as long as you change the Colors and don't use the Ghent university font (which is specifically theirs) the template itself can be considered MiT, but I have a better and improved version I can send you if you want, it has a lot of fixes for annexes

**Comment by bbinet** [comment]
Sure, I won't use the same colors and the font.
If you have an improved version of your template, I'm of course happy the get the new version.
Thanks a lot for this great template!

**Comment by Dherse** [comment]
I'll try to send push a commit tonight (if I find the motivation 😂) and I'll ping you here then ;)

**Comment by bbinet** [comment]
Thank you :smile:

**Comment by Dherse** [comment]
@bbinet Sorry, I was sick for the past couple of days, I just pushed some commits with fixes, a license, and further details on usage.

**Comment by bbinet** [comment]
Thanks a lot!
And good recovery to you.
